### PR TITLE
vNext Sample and updated readme

### LINKED ISSUE #413: Getting HumanizerMetadataProvider to work in vNext (ASP.NET 5 Sample project)
Seems like `DataAnnotationsModelMetadataProvider` is gone in vNext. Instead there is a `DataAnnotationsMetadataProvider` but it doesn't expose any virtual members to override.

This is my attempt based on the `DefaultModelMetadataProvider` not sure if this is the right way to go:

``` csharp

public class HumanizerMetadataProvider : DefaultModelMetadataProvider
{
    protected override ModelMetadata CreateModelMetadata(DefaultMetadataDetailsCache entry)
    {
        var propertyAttributes = entry.Attributes;
        var modelMetadata = entry.DisplayMetadata;

        if (IsTransformRequired(modelMetadata, propertyAttributes))
            modelMetadata.DisplayName = modelMetadata.SimpleDisplayProperty.Humanize().Transform(To.TitleCase);

        return base.CreateModelMetadata(entry);
    }


    private static bool IsTransformRequired(DisplayMetadata modelMetadata, IReadOnlyList<object> propertyAttributes)
    {
        if (string.IsNullOrEmpty(modelMetadata.SimpleDisplayProperty))
            return false;

        if (propertyAttributes.OfType<DisplayNameAttribute>().Any())
            return false;

        if (propertyAttributes.OfType<DisplayAttribute>().Any())
            return false;

        return true;
    }

    public HumanizerMetadataProvider(ICompositeMetadataDetailsProvider detailsProvider) : base(detailsProvider)
    {
    }
}
```

I still haven't figured out how to plug this in so that it replaces the default.

### PR DESCRIPTION
**Pull request by mrchief**
Just realized I've been sitting on it for so long. I remember that you wanted me to merge with your latest and seems like I forgot to send the PR after doing so. Anyway, I merged master again and here it is!

Fixes #413

### CODE REVIEW

**Comment by onovotny** [comment]
Can you please rebase this on a new branch from `dev`? Thanks!

**Comment by mrchief** [comment]
Sure. Should I rollback master branch or leave it as is?

**Comment by onovotny** [comment]
Master has been fully merged into dev at this point...not sure what you're asking otherwise :)

**Comment by mrchief** [comment]
The master in my fork has these 4 commits (with the sample and readme). If I'm applying that in dev branch, do you still want my PR to contain those 4 commits in master?

**Comment by onovotny** [comment]
I thought a PR can only have a single branch it's sourced from? in general, I tend to recommend using the "GitHub Flow" model of never making PR changes into `master` and always using a branch. Then I'll pull/reset --hard on my fork's master to the upstream master to keep them in sync.

So if you can rebase into a branch off of the current dev, I think you'll need to submit a new PR with just those four commits. Then if you want to get your master back in sync, you can do a git reset --hard pointing to the head commit from the main repo.

**Comment by mrchief** [comment]
Sorry, spoke too soon! Sent a new PR off dev branch. Closing this.

**Pull request closed without merging**
