### PR TITLE
Add lionbridge translations of fil-PH, ko-KR, ms-MY, and th-TH

### PR DESCRIPTION
**Pull request by onovotny**
I got a free credit for some translation services from Lionbridge and used them to translate the ResX's to four languages not currently supported: 

Filipino
Korean
Malay
Thai

It would be helpful to have a review from someone to validate

### CODE REVIEW

**Comment by aloisdg** [comment]
An idea, would be to export them to csv and ask for a review on reddit (/r/translation for example) or somewhere else on internet.

**Comment by MehdiK** [comment]
This has been here for almost two years. Do you mind if we close it?

**Comment by hazzik** [comment]
@mehdik I think just merge it.

**Comment by MehdiK** [comment]
Can do. There is now a conflict on the branch @onovotny. Could you do a rebase please? Thanks.

**Comment by onovotny** [comment]
@MehdiK just rebased. I didn't merge yet only because there hasn't been any human review of the translations as a sanity check.

**Comment by onovotny** [comment]
wait, the nuspecs are wrong...don't merge yet.

**Comment by onovotny** [comment]
Fixed, should be good now.

**Comment by MehdiK** [comment]
Thanks @onovotny. We have unit tests for all other localisations. This doesn't have unit tests, which is kinda fair, considering it's unverified. Do you think that having tests will help when someone from those languages wants to contribute a fix?

**Comment by onovotny** [comment]
I'm honestly not sure what the right approach is here. Gets down to the purpose of the tests; if it's verifying that the right resources gets returned based on the culture, then perhaps... 

If it's verifying all of the strings, then it may be overkill to have a full suite without any verification.

Maybe a simple test per language that ensures at least one of the correct strings is pulled from the resources?

**Comment by MehdiK** [comment]
Easy to add the tests if and when someone wants to change the provided translations. Thanks for your patience.

**Comment by justinyoo** [comment]
As of the given `Resources.ko-KR.resx`, I confirm that it is fine. However, I'm not sure how #496 has been treated.

**Pull request merged**
