### PR TITLE
Add Luxembourgish localisation

### PR DESCRIPTION
**Pull request by igotinfected**
This PR includes Luxembourgish localisation based on a mix of implementations for different languages (i.e. German, French, Icelandic, ...). The most annoying part is dealing with the `Eifeler Regel`, where an `n` must be removed from a word based on a number of factors (punctuation, location within sentence, and most importantly, the first letter of the following word).

Here is a checklist you should tick through before submitting a pull request: 
 - [x] Implementation is clean
 - [x] Code adheres to the existing coding standards; e.g. no curlies for one-line blocks, no redundant empty lines between methods or code blocks, spaces rather than tabs, etc.
 - [x] No Code Analysis warnings
 - [x] There is proper unit test coverage
 - [x] If the code is copied from StackOverflow (or a blog or OSS) full disclosure is included. That includes required license files and/or file headers explaining where the code came from with proper attribution
 - [x] There are very few or no comments (because comments shouldn't be needed if you write clean code)
 - [x] Xml documentation is added/updated for the addition/change
 - [x] Your PR is (re)based on top of the latest commits from the `main` branch (more info below)
 - [x] Link to the issue(s) you're fixing from your PR description. Use `fixes #<the issue number>`
 - [x] Readme is updated if you change an existing feature or add a new one
 - [x] Run either `build.cmd` or `build.ps1` and ensure there are no test failures

### CODE REVIEW

**Comment by igotinfected** [comment]
Hey 👋🏼 @clairernovotny @hazzik 

I would like to integrate Humanizer into our internal tools, it would be ideal to have Luxembourgish included when I do (we usually support the 4 major languages, English, French, German, and Luxembourgish). Would you be able to provide me with a very approximate ETA on if/when this could be merged and released? I'm not in a major rush -- just seeing as the last release dates back a year I'd like to have an idea of whether I should look into publishing something privately for our use-case 😉

**Review by hangy — APPROVED** [review]

**Comment by SimonCropp** [comment]
@igotinfected  can you rebase

**Comment by igotinfected** [comment]
> @igotinfected can you rebase

Done! Struggling with some `Fr` and `He` tests failing locally randomly, don't think it's related to my changes though.

Big thanks to you and everyone involved for reviving the project :)

**Comment by SimonCropp** [comment]
thanks

> Struggling with some Fr and He tests failing locally randomly

yeah i have not worked out the cause of those. and not related to your changes

**Pull request merged**
