### PR TITLE
Refactor DateTime and TimeSpan humanization to use ToQuantity extension #205

### PR DESCRIPTION
**Pull request by alimeziane**
I have add  ShowQuantityAs option to timeSpan and DateTime humanization.

### CODE REVIEW

**Comment by alimeziane** [comment]
I added to TimeSpan and DateTime humanization the ability to choose using ShowQuantityAs display amounts by number or letter. My development is based on the existing features of towords to avoid redudancies.
Examples :

**Comment by onovotny** [comment]
What is the current status of this? Is it feature complete?

**Comment by onovotny** [comment]
Ping?

**Comment by MehdiK** [comment]
This PR has been sitting here for 2.5 years with no updates. I was going to review it but it also has too many conflicts now. I am closing it. Happy to review it once the conflicts are resolved @alimeziane.

**Pull request closed without merging**
