### PR TITLE
Add Chinese version of ToWords

### PR DESCRIPTION
**Pull request by sunh3**
Hey there,

I found your project and it is awesome, I made a simplified Chinese translation for ToWords feature, hope you like it. Unit tests all pass, msbuild pass. Let me know if I missed anything.

Cheers
Eric

### CODE REVIEW

**Comment by MehdiK** [comment]
@sunh3 could you please address the above comment? I will revisit this in two weeks and will close it off if not addressed by then. Thanks.

**Comment by sunh3** [comment]
@MehdiK Hey I'll have a look of it, thanks

**Comment by sunh3** [comment]
@MehdiK Hey it looks like AppVeyor doesn't support zh-CN, https://www.screencast.com/t/pFCh4QtnXGDa
I can see there are other files containing chinese words in the same folder, https://www.screencast.com/t/igUmhlVM, I wonder how they pass the build.
Let me know if anything I can do from my end. thanks

**Comment by MehdiK** [comment]
Thanks @sunh3. That is strange. Do all tests pass on your machine?

**Comment by sunh3** [comment]
Hi @MehdiK , turns out one of the tests did failed (odd I was so sure all passed on my local...), I made the fix and it looks all good.

**Comment by MehdiK** [comment]
Great. Merged. Thanks.

**Pull request merged**
