### PR TITLE
Belgian french support for NumberToWords and NumberToOrdinalWords

### LINKED ISSUE #538: Belgian french support for NumberToWords and NumberToOrdinalWords
In Walloon region we don't use same "soixante-dix" as French people but "septante" instead.

[See documentation here](http://www.languagesandnumbers.com/comment-compter-en-francais-belgique/fr/fra-bel/)

Already forked and implemented.
PR coming.

### PR DESCRIPTION
**Pull request by jaxx-rep**
In Walloon region we don't use same "soixante-dix" as French people but "septante" instead.

[See documentation here]

Fixes #538

### CODE REVIEW

**Comment by aloisdg** [comment]
It could be nice to add octante and nonante (swiss french) in another feature.

**Comment by jaxx-rep** [comment]
Sure, i'll cancel this PR and include fr-CH culture

**Comment by aloisdg** [comment]
@jaxx-rep why cancel it? You could made two smalls PR, one for each. :smile:

**Comment by jaxx-rep** [comment]
Because of facts ;p

I was not happy with my naive implementation, add fr-CH this way was a step in maintenance nightmare.

**Comment by aloisdg** [comment]
Nice!

**Pull request closed without merging**
