### PR TITLE
 fix neuter romanian words

### PR DESCRIPTION
**Pull request by totpero**
Here is a checklist you should tick through before submitting a pull request: 
 - [x] Implementation is clean
 - [x] Code adheres to the existing coding standards; e.g. no curlies for one-line blocks, no redundant empty lines between methods or code blocks, spaces rather than tabs, etc.
 - [x] No ReSharper warnings
 - [x] There is proper unit test coverage
 - [x] If the code is copied from StackOverflow (or a blog or OSS) full disclosure is included. That includes required license files and/or file headers explaining where the code came from with proper attribution
 - [x] There are very few or no comments (because comments shouldn't be needed if you write clean code)
 - [x] Xml documentation is added/updated for the addition/change
 - [x] Your PR is (re)based on top of the latest commits from the `dev` branch (more info below)
 - [x] Link to the issue(s) you're fixing from your PR description. Use `fixes #<the issue number>`
 - [x] Readme is updated if you change an existing feature or add a new one
 - [x] Run either `build.cmd` or `build.ps1` and ensure there are no test failures

### CODE REVIEW

**Comment by MehdiK** [comment]
Thanks for the contribution @totpero. There is a conflict. Please pull-rebase the latest and push. Please leave a comment here when done and I will merge.

**Comment by totpero** [comment]
I have fix the rebase, check if is ok. Thanks

**Comment by onovotny** [comment]
bypassing CLA due to the age of this PR

**Comment by onovotny** [comment]
thanks!

**Pull request merged**
