### PR TITLE
Implement sv (Swedish/Sweden) for Number to Word

### LINKED ISSUE #857: Swedish Number to Word doesn't exist

### PR DESCRIPTION
**Pull request by haf**
Here is a checklist you should tick through before submitting a pull request: 
 - [x] Implementation is clean
 - [x] Code adheres to the existing coding standards; e.g. no curlies for one-line blocks, no redundant empty lines between methods or code blocks, spaces rather than tabs, etc.
 - [x] No ReSharper warnings
 - [x] There is proper unit test coverage
 - [x] If the code is copied from StackOverflow (or a blog or OSS) full disclosure is included. That includes required license files and/or file headers explaining where the code came from with proper attribution
 - [x] There are very few or no comments (because comments shouldn't be needed if you write clean code — this justification is wrong, they are still needed. Perhaps you've never worked with someone who's articulate.)
 - [ ] Xml documentation is added/updated for the addition/change — not really
 - [ ] Your PR is (re)based on top of the latest commits from the `dev` branch (more info below) — there's no `dev` branch in `origin`.
 - [x] Link to the issue(s) you're fixing from your PR description. Use `fixes #<the issue number>`
 - [ ] Readme is updated if you change an existing feature or add a new one — not applicable
 - [ ] Run either `build.cmd` or `build.ps1` and ensure there are no test failures — no can do, I'm on macOS

Fixes #857

### CODE REVIEW

**Comment by onovotny** [comment]
Thanks!

**Comment by haf** [comment]
You're welcome!

**Comment by haf** [comment]
When do you think you can release this as a nuget?

**Comment by onovotny** [comment]
2.7.9 is rolling out to NuGet now...probably 15 min to an hour for NuGet "indexing" for it to show up.

**Comment by haf** [comment]
Sweet! 🧨

**Pull request merged**
