### PR TITLE
Fixes #518

### LINKED ISSUE #518: Number to number extensions
I think it would be nice to add to the convenient extensions for `TimeSpan`, `ByteSize` extensions that simplify writing big numbers, for example:

    int size = 20.Millions();

Instead of:

    int size = 20000000;

It's clearer to read, simpler to write and reduces the chance for errors.

I plan on using this extensively in my configuration defaults (e.g. `BounedCapacity = 10.Millions()`, `MaxDegreeOfParallelism = 1.Thousands()`)

### PR DESCRIPTION
**Pull request by i3arnon**
This change is [Reviewable](https://reviewable.io/reviews/humanizr/humanizer/519)

### CODE REVIEW

**Comment by mexx** [comment]
@i3arnon Thank you for your contribution.

Please update the readme.md, I think it's worth adding a new section like the `Fluent Date` one.

**Comment by mexx** [comment]
fixes #518 
GitHub doesn't link the PR and the issue when it's in title, it has to be in comment.

**Comment by hazzik** [comment]
I think we need to mark these methods with `[MethodImpl(MethodImplOptions.AggressiveInlining)]`

**Comment by hazzik** [comment]
Also, I concern about "billions". In a "real world" there are "long scale" and "short scale". We need to describe explicitly what scale do we use (it's short)

**Comment by i3arnon** [comment]
So... what do you guys think?

**Comment by onovotny** [comment]
Pinging @mexx @hazzik?

**Comment by aloisdg** [comment]
Any update on this? @i3arnon @mexx @hazzik

**Comment by mexx** [comment]
LGTM

**Comment by onovotny** [comment]
Rebased and merged in, thanks!

**Pull request closed without merging**
