### PR TITLE
Add ability to build with mono xbuild

### PR DESCRIPTION
**Pull request by hazzik**
- Solves #422
- I had to change xunit.runner.msbuild to xunit.console.clr4, because MSBuild task fails to run on mono, as it can not find some libraries.
- I had to update ApprovalTests because otherwise it fails with SecurityException trying to access registry to find a VS path.
- Api approver test failing because of https://github.com/approvals/ApprovalTests.Net/pull/122

### CODE REVIEW

**Comment by MehdiK** [comment]
This is what I get:

```
XBuild Engine Version 12.0
Mono, Version 4.0.1.0
Copyright (C) 2005-2013 Various Mono authors
			Configuration: Release Platform: AnyCPU
		Configuration: Release Platform: AnyCPU
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll: cannot execute binary file
/var/folders/zx/z392pnd11xb1yclwcfc1fdg40000gp/T/tmp1413d305.tmp: line 1: src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll: cannot execute binary file
/Users/mehdikhalili/_mine/Humanizer/build.proj: error : Command 'mono "tools/xunit/xunit.console.clr4.exe" /silent src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll;src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll;src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll;src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll;src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll;src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll;src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll;src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll;src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll;src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll;src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll;src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll;src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll;src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll;src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll;src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll;src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll;src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll;src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll;src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll;src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll;src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll;src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll;src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll;src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll;src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll;src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll;src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll;src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll;src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll;src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll;src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll;src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll;src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll;src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll;src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll;src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll;src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll;src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll;src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll;src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll;src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll;src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll;src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll;src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll;src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll;src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll;src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll;src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll;src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll;src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll;src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll;src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll;src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll;src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll;src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll;src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll;src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll;src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll;src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll;src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll;src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll;src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll;src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll;src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll;src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll;src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll;src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll;src/Humanizer.Tests/bin/Release/Humanizer.Tests.dll;src/Humanizer.Tests/obj/Release/Humanizer.Tests.dll' exited with code: 126.
```

**Comment by hazzik** [comment]
"cannot execute binary file" this is when xunit tries to output "." dot for every file.

**Comment by hazzik** [comment]
And it returns "126" because of ApiApproval test

**Comment by MehdiK** [comment]
> "cannot execute binary file" this is when xunit tries to output "." dot for every file.

Thanks @hazzik. What can we do to fix this?

**Comment by hazzik** [comment]
@MehdiK this is what /silent suppose to do, but I'm not sure, I'll check probably today

**Comment by hazzik** [comment]
Actually, if you have time, you can try to run xbuild build.proj to see the full output

**Comment by hazzik** [comment]
Also, probably (I'm not sure thou) that this "cannot execute binary file" are originated from ApiApproval when it tries to launch the diff program.

**Comment by hazzik** [comment]
I had to update ApiApproval, to correctly generate API definition on mono, as cecil is more stable that reflection api. But now it fails on [CodeTypeReference](https://github.com/MehdiK/Humanizer/commit/ebe21620799528c27736b8a8a0bf26e52c79f690?diff=unified#diff-7f456362180a852610c8dcc2e5c3a423R763) on array of objects.

**Comment by hazzik** [comment]
Currently not possible due https://github.com/GitTools/GitVersion/issues/264

**Comment by hazzik** [comment]
https://github.com/GitTools/GitVersion/issues/264 has been solved

**Comment by hazzik** [comment]
Not possible due xbuild is unable to build project.json

**Comment by onovotny** [comment]
xbuild is very old and not supported. The project should work with the .NET Core SDK and `dotnet build`.

**Comment by MarkWhybird** [comment]
Thanks - I will look at what's going on tonight; all I did was make sure I had the latest version of VS (and also XCode, but not sure really why I even mentioned that in this case), loaded up the project, and pressed the Build button in VS. I'll get back with more detail tonight (about 6-8 hours from now?), just was intrigued as to if it is supposed to just work out-of-the-box these days. Seems the answer is yes; appreciated.

**Pull request closed without merging**
