### PR TITLE
Added Invariant Culture to rendering of constants

### PR DESCRIPTION
**Pull request by rdoubleui**
Added Invariant Culture to rendering of constants in ApiApprover addressing issue #474

### CODE REVIEW

**Comment by onovotny** [comment]
My one concern is that this file is content that's automatically included from the ApiApprover library and that changes will be lost upon upgrade. This fix should also be submitted to it as well.

**Comment by MehdiK** [comment]
What do you think about this @JakeGinnivan?

**Comment by JakeGinnivan** [comment]
Agree, should fix downstream then usage the package. This can be a temp fix but the upgrade will be as smooth

Sent from my Windows Phone
________________________________

**Comment by rdoubleui** [comment]
@onovotny So should this be closed then? Anything I need to do here?

**Comment by MehdiK** [comment]
Thanks for the PR. If you could submit this PR against APIApprover Jake
will merge it in and release it and Humanizer will be fixed through
dependency. Thanks.

**Comment by rdoubleui** [comment]
Ok, did that. Closing it here.

**Pull request closed without merging**
