### PR TITLE
fixed Issue 1186

### LINKED ISSUE #1186: `DateOnly` has current date return 'today'
When you want to humanize the `DateOnly` that has current date return 'now'.it's better to return 'today'. 'now' Word referee current date and time but 'today' referee only current date

### PR DESCRIPTION
**Pull request by hemalshah28**
Here is a checklist you should tick through before submitting a pull request: 
 - [x] Implementation is clean
 - [x] Code adheres to the existing coding standards; e.g. no curlies for one-line blocks, no redundant empty lines between methods or code blocks, spaces rather than tabs, etc.
 - [x] No Code Analysis warnings
 - [x] There is proper unit test coverage
 - [x] If the code is copied from StackOverflow (or a blog or OSS) full disclosure is included. That includes required license files and/or file headers explaining where the code came from with proper attribution
 - [x] There are very few or no comments (because comments shouldn't be needed if you write clean code)
 - [x] Xml documentation is added/updated for the addition/change
 - [x] Your PR is (re)based on top of the latest commits from the `main` branch (more info below)
 - [x] Link to the issue(s) you're fixing from your PR description. Use `fixes #1186 `
 - [x] Readme is updated if you change an existing feature or add a new one
 - [x] Run either `build.cmd` or `build.ps1` and ensure there are no test failures

### CODE REVIEW

**Comment by behroozbc** [comment]
Hi, I think your implementation isn't accurate. You need to implement `DateOnly` and not use `DateTime`. Nevertheless, I see you use the `DateTime`.

**Review by behroozbc — CHANGES_REQUESTED** [review]
Hi, I think your implementation isn't accurate. You need to implement `DateOnly` and not use `DateTime`. Nevertheless, I see you use the `DateTime`.

**Comment by hemalshah28** [comment]
> Hi, I think your implementation isn't accurate. You need to implement `DateOnly` and not use `DateTime`. Nevertheless, I see you use the `DateTime`.
Ok, Let me look into it.

**Comment by hemalshah28** [comment]
@behroozbc , please take a look and let me know. sorry for misunderstanding.

**Comment by hemalshah28** [comment]
I was looking for some help.

**Pull request closed without merging**
