### PR TITLE
Use collection formatter when humanizing timespans. Fixes #497

### LINKED ISSUE #497: Add option to customize list of time indicators of humanized timespans
Probably this title needs some explanation ;) When you humanize a timespan, like this:

````csharp
        const int ONE_WEEK_ONE_DAY = 8;
        var oneWeekOneDayTimeSpan = TimeSpan.FromDays(ONE_WEEK_ONE_DAY);
        var result = oneWeekOneDayTimeSpan.Humanize(2);
````

then you get "1 week, 1 day". However, what I want is to have the option to override the concatenation of the strings, to have an ", and", instead of only a comma between the second to last, and last item, making the output this:

    1 week, and 1 day

[AFAICT](https://github.com/Humanizr/Humanizer/blob/008ce148f814ed0833aee937870c57aed74e16ec/src/Humanizer/TimeSpanHumanizeExtensions.cs#L187), you cannot do this now with Humanizer, and couldn't find an issue for this. I'd suggest adding a `separator` argument to the call, similar to how you can specify that on the [`Humanize` call for collections](https://github.com/Humanizr/Humanizer/blob/008ce148f814ed0833aee937870c57aed74e16ec/src/Humanizer/CollectionHumanizeExtensions.cs#L41). However, I'm not sure if you want another overload for this, besides the [other](https://github.com/Humanizr/Humanizer/blob/008ce148f814ed0833aee937870c57aed74e16ec/src/Humanizer/TimeSpanHumanizeExtensions.cs#L28) [two](https://github.com/Humanizr/Humanizer/blob/008ce148f814ed0833aee937870c57aed74e16ec/src/Humanizer/TimeSpanHumanizeExtensions.cs#L43).

I'm happy to make a PR, if my proposal is accepted, and we can find a good way to add it to the API.

### PR DESCRIPTION
**Pull request by ErikSchierboom**

### CODE REVIEW

**Comment by mexx** [comment]
The code looks good to me.
Maybe we could make it non breaking, by defaulting to the old value?

If one would love to have the standard collection format behavior, she can send `null` in.

We can look at the defaults and making breaking when the discussion of global config design in #508 comes to a conclusion and the new way of doing things is clear, what do you think?

**Comment by ErikSchierboom** [comment]
@mexx I have made the requested change, making this PR non-breaking.

**Comment by mexx** [comment]
Sorry, but there is one more thing. Please document this parameter in the readme.md

**Comment by ErikSchierboom** [comment]
@mexx The `readme.md` file has now also been updated.

**Comment by mexx** [comment]
LGTM, @onovotny do you mind to merge it?

**Pull request merged**
