### PR TITLE
Refactor packages to enable excluding locales

### PR DESCRIPTION
**Pull request by onovotny**
This PR tracks #59

### CODE REVIEW

**Comment by MehdiK** [comment]
Looks good. Thanks @onovotny.

**Comment by MehdiK** [comment]
I am just a bit unsure about `Humanizer.all` name although I'm not sure what else I would call it!

**Comment by MehdiK** [comment]
I am just thinking that when/if there are other packages as part of the library, then `all` implies everything while we just mean all the resources.

**Comment by onovotny** [comment]
So right now, I have `Humanizer` as the meta-package that pull in every Locale and `Humanizer.Core`. Essentially, it preserves current behavior.

For people that don't want all locales, they can just directly install the `Humanizer.Core` package.

Nothing has changed with the dll's or their names, it's all just packaging.

**Comment by MehdiK** [comment]
Nice :+1:

**Comment by onovotny** [comment]
Testing on UWP has turned up an error installing the localized packages...a false error I believe. @Emgarten, can you please assist (email with details should be in your inbox)

**Comment by onovotny** [comment]
@Emgarten: easy repro, check out the `features/integration` branch and try to add `Humanizer.Core.ar` to it via NuGet. You'll see an error about it not being compatible with a UWP app. If you add to the project.json manually, you get that error on build instead.

**Comment by onovotny** [comment]
There's a fix for this but it's dependent on this PR being merged in (and shipped to the public):
https://github.com/NuGet/NuGet.Client/pull/95

**Pull request merged**
