### PR TITLE
As was to were irregularity

### PR DESCRIPTION
**Pull request by gungora**

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/Humanizr/Humanizer?pullRequest=1244) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/Humanizr/Humanizer?pullRequest=1244) before we can accept your contribution.<br/><br/>:x: gungora [sign now](https://cla.dotnetfoundation.org/Humanizr/Humanizer?pullRequest=1244)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/Humanizr/Humanizer?pullRequest=1244) it.</sub>

**Comment by SimonCropp** [comment]
@gungora can you sign the cla

**Comment by gungora** [comment]
@dotnet-policy-service agree

**Comment by SimonCropp** [comment]
@gungora thanks for the contribution

**Pull request merged**
