### PR TITLE
Add Esperanto support to NumberToWords. Fixes #558

### LINKED ISSUE #558: Add Esperanto support for NumberToWords
Hello,

I am adding esperanto support for NumberToWords.

Cheers,

### PR DESCRIPTION
**Pull request by aloisdg**
Here is a checklist you should tick through before submitting a pull request: 
- [x] Implementation is clean
- [x] Code adheres to the existing coding standards; e.g. no curlies for one-line blocks, no redundant empty lines between methods or code blocks, spaces rather than tabs, etc.
- [ ] No ReSharper warnings (Is there a global R# file?)
- [x] There is proper unit test coverage
- [x] If the code is copied from StackOverflow (or a blog or OSS) full disclosure is included. That includes required license files and/or file headers explaining where the code came from with proper attribution
- [x] There are very few or no comments (because comments shouldn't be needed if you write clean code)
- [ ] Xml documentation is added/updated for the addition/change (needed?)
- [x] Your PR is (re)based on top of the latest commits from the `dev` branch (more info below)
- [x] Link to the issue(s) you're fixing from your PR description. Use `fixes #<the issue number>`
- [ ] Readme is updated if you change an existing feature or add a new one (Is there a list of language supported?)
- [ ] Run either `build.cmd` or `build.ps1` and ensure there are no test failures (failed but work in VS)

### CODE REVIEW

**Comment by aloisdg** [comment]
How can I see the log of AppVeyor? I get `— AppVeyor was unable to build non-mergeable pull request` but I find it not very helpful.

**Comment by hangy** [comment]
No idea on how to get the log (might only be visible to an admin), but I just ran the build.cmd on your branch and it built just fine. Maybe just a transient error?

**Comment by aloisdg** [comment]
@hangy Thank you for your feedback

**Comment by hazzik** [comment]
@onovotny can you take a look?

**Comment by onovotny** [comment]
@hazzik @aloisdg I had to revert as I saw build errors: Build fails with `eo-EO` is an invalid culture identifier

**Pull request merged**
