### PR TITLE
Implements ToWords and ToWordsOrdinal for fr-BE and fr-CH. 

### LINKED ISSUE #538: Belgian french support for NumberToWords and NumberToOrdinalWords
In Walloon region we don't use same "soixante-dix" as French people but "septante" instead.

[See documentation here](http://www.languagesandnumbers.com/comment-compter-en-francais-belgique/fr/fra-bel/)

Already forked and implemented.
PR coming.

### PR DESCRIPTION
**Pull request by hazzik**
Fixes #538, #541, #548, #557

### CODE REVIEW

**Comment by hazzik** [comment]
@jaxx-rep, @Xiaoy312, @aloisdg, @ghigad please review

**Comment by Tradioyes** [comment]
Looks good to me :+1:

**Comment by onovotny** [comment]
@hazzik Feel free to merge in when you and @aloisdg are satisfied

**Pull request merged**
