### PR TITLE
#1245: Replace the greek B (Beta) char to a regular B in method

### PR DESCRIPTION
**Pull request by vilinet**
Fixes a character encoding problem, related to a 'B' char in a method. See the details in the related ticket: #1245 

This PR simply replaces that special B char to a regular B char.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/Humanizr/Humanizer?pullRequest=1246) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/Humanizr/Humanizer?pullRequest=1246) before we can accept your contribution.<br/><br/>:x: vilinet [sign now](https://cla.dotnetfoundation.org/Humanizr/Humanizer?pullRequest=1246)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/Humanizr/Humanizer?pullRequest=1246) it.</sub>

**Comment by AmrAlSayed0** [comment]
Please accept this PR, this issue is causing the AOT compiler to fail

```
7>  [aot-compiler stderr] obj\\Release\\130\\aot\\armeabi-v7a\\Humanizer.dll\\temp.s:2441:84: error: unexpected token in argument list (TaskId:1658)
7>  [aot-compiler stderr] ldr pc,=Humanizer_Localisation_NumberToWords_GreekNumberToWordsConverter_ConvertInt╬_13_long_bool (TaskId:1658)
7>  [aot-compiler stderr] obj\\Release\\130\\aot\\armeabi-v7a\\Humanizer.dll\\temp.s:7603:86: error: unexpected token in operand (TaskId:1658)
7>  [aot-compiler stderr] p_375_plt_Humanizer_Localisation_NumberToWords_GreekNumberToWordsConverter_ConvertInt╬_13_long_bool_llvm: (TaskId:1658)
7>  [aot-compiler stderr] obj\\Release\\130\\aot\\armeabi-v7a\\Humanizer.dll\\temp.s:7604:94: error: unexpected token (TaskId:1658)
7>  [aot-compiler stderr]         .globl p_375_plt_Humanizer_Localisation_NumberToWords_GreekNumberToWordsConverter_ConvertInt╬_13_long_bool_llvm (TaskId:1658)
7>  [aot-compiler stderr] obj\\Release\\130\\aot\\armeabi-v7a\\Humanizer.dll\\temp.s:7605:93: error: expected STT_<TYPE_IN_UPPER_CASE>, '#<type>', '%<type>' or "<type>" (TaskId:1658)
7>  [aot-compiler stderr]         .type p_375_plt_Humanizer_Localisation_NumberToWords_GreekNumberToWordsConverter_ConvertInt╬_13_long_bool_llvm,#function (TaskId:1658)
7>  [aot-compiler stderr] obj\\Release\\130\\aot\\armeabi-v7a\\Humanizer.dll\\temp.s:7606:88: error: unexpected token in directive (TaskId:1658)
7>  [aot-compiler stderr]         .local plt_Humanizer_Localisation_NumberToWords_GreekNumberToWordsConverter_ConvertInt╬_13_long_bool (TaskId:1658)
7>  [aot-compiler stderr] obj\\Release\\130\\aot\\armeabi-v7a\\Humanizer.dll\\temp.s:7607:87: error: expected STT_<TYPE_IN_UPPER_CASE>, '#<type>', '%<type>' or "<type>" (TaskId:1658)
7>  [aot-compiler stderr]         .type plt_Humanizer_Localisation_NumberToWords_GreekNumberToWordsConverter_ConvertInt╬_13_long_bool,#function (TaskId:1658)
7>  [aot-compiler stderr] obj\\Release\\130\\aot\\armeabi-v7a\\Humanizer.dll\\temp.s:7608:80: error: unexpected token in operand (TaskId:1658)
7>  [aot-compiler stderr] plt_Humanizer_Localisation_NumberToWords_GreekNumberToWordsConverter_ConvertInt╬_13_long_bool: (TaskId:1658)
7>  [aot-compiler stderr] obj\\Release\\130\\aot\\armeabi-v7a\\Humanizer.dll\\temp.s:7613:87: error: unexpected token in directive (TaskId:1658)
7>  [aot-compiler stderr]         .size plt_Humanizer_Localisation_NumberToWords_GreekNumberToWordsConverter_ConvertInt╬_13_long_bool,.-plt_Humanizer_Localisation_NumberToWords_GreekNumberToWordsConverter_ConvertInt╬_13_long_bool (TaskId:1658)
7>  [aot-compiler stdout] Running: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\MSBuild\\Xamarin\\Android\\binutils\\bin\\llvm-mc.exe" --arch=arm --triple=arm-linux-gnu --assemble --filetype=obj --mattr=+armv7-a,+vfp3 -o=obj\Release\130\aot\armeabi-v7a\Humanizer.dll\temp.s.o obj\Release\130\aot\armeabi-v7a\Humanizer.dll\temp.s (TaskId:1658)
7>  [aot-compiler stdout] Running: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\MSBuild\\Xamarin\\Android\\binutils\\bin\\llvm-mc.exe" --arch=arm --triple=arm-linux-gnu --assemble --filetype=obj --mattr=+armv7-a,+vfp3 -o=obj\Release\130\aot\armeabi-v7a\Humanizer.dll\temp-llvm.o obj\Release\130\aot\armeabi-v7a\Humanizer.dll\temp-llvm.s (TaskId:1658)
7>  [aot-compiler stderr] ld: error: cannot open obj\Release\130\aot\armeabi-v7a\Humanizer.dll\temp.s.o: no such file or directory (TaskId:1658)
7>  [aot-compiler stderr] C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\binutils\bin\llvm-strip.exe: error: 'obj\Release\130\aot\armeabi-v7a\libaot-Humanizer.dll.so.tmp': no such file or directory (TaskId:1658)
```

**Comment by vilinet** [comment]
> 

@dotnet-policy-service agree

**Comment by vilinet** [comment]
> @dotnet-policy-service agree

@dotnet-policy-service agree

**Comment by SimonCropp** [comment]
thanks for the contribution

**Pull request merged**
