### PR TITLE
Fix Japanese single year translation

### LINKED ISSUE #1049: Years translation issue on Japanese - version 2.7.9 for C# .NET
Humanizing a `TimeSpan` instance in Japanese is generating wrong text.
Running this line `....Humanize(precision: 2, maxUnit: TimeUnit.Year, minUnit: TimeUnit.Month)` on a `TimeSpan` instance will produce "1 年間の" for "1 year" instead of "1年", for 2 year and above it produces the right text e.g. "2 年", "3 年", etc.

### PR DESCRIPTION
**Pull request by Cheesebaron**
Fixes #1049 Japanese single year translation.

I am not a native Japanese speaker, so would be nice to get a confirmation that this is actually the correct way to translate it.

Here is a checklist you should tick through before submitting a pull request: 
 - [x] Implementation is clean
 - [x] Code adheres to the existing coding standards; e.g. no curlies for one-line blocks, no redundant empty lines between methods or code blocks, spaces rather than tabs, etc.
 - [ ] No Code Analysis warnings
 - [ ] There is proper unit test coverage
 - [ ] If the code is copied from StackOverflow (or a blog or OSS) full disclosure is included. That includes required license files and/or file headers explaining where the code came from with proper attribution
 - [x] There are very few or no comments (because comments shouldn't be needed if you write clean code)
 - [ ] Xml documentation is added/updated for the addition/change
 - [x] Your PR is (re)based on top of the latest commits from the `dev` branch (more info below)
 - [x] Link to the issue(s) you're fixing from your PR description. Use `fixes #<the issue number>`
 - [ ] Readme is updated if you change an existing feature or add a new one
 - [x] Run either `build.cmd` or `build.ps1` and ensure there are no test failures

### CODE REVIEW

**Comment by SimonCropp** [comment]
thanks for the contribution

**Comment by Cheesebaron** [comment]
@SimonCropp let me know if this needs more work such as rebasing etc. Happy to do it.

**Comment by SimonCropp** [comment]
@Cheesebaron thanks. some tests need fixing

**Comment by Cheesebaron** [comment]
I see that. Will commit a fix for it :)

**Pull request merged**
