### PR TITLE
Sort ignoring article prefixes

### LINKED ISSUE #694: Sort strings ignoring culture specific article word prefixes
Let's say we have the following list, it would be great if we could sort it while ignoring article words like the and a:
```c#
var items = new [] { "Banana", "Fork", "The apple" };
var sorted = items.OrderBy(i => i.HumanizeSortPrefixes());
sorted.ForEach(i => Console.WriteLine(i));
```
with output:
```
The apple
Banana
Fork
```
I'm not really sold on the method name though..

### PR DESCRIPTION
**Pull request by christopherie**
fixes #694

Here is a checklist you should tick through before submitting a pull request: 

 - [X] Implementation is clean
 - [X] Code adheres to the existing coding standards; e.g. no curlies for one-line blocks, no redundant empty lines between methods or code blocks, spaces rather than tabs, etc.
 - [X] No ReSharper warnings
 - [X] There is proper unit test coverage
 - [ ] If the code is copied from StackOverflow (or a blog or OSS) full disclosure is included. That includes required license files and/or file headers explaining where the code came from with proper attribution
 - [X] There are very few or no comments (because comments shouldn't be needed if you write clean code)
 - [ ] Xml documentation is added/updated for the addition/change
 - [X] Your PR is (re)based on top of the latest commits from the `dev` branch (more info below)
 - [X] Link to the issue(s) you're fixing from your PR description. Use `fixes #<the issue number>`
 - [ ] Readme is updated if you change an existing feature or add a new one
 - [X] Run either `build.cmd` or `build.ps1` and ensure there are no test failures

### CODE REVIEW

**Comment by christopherie** [comment]
@MehdiK could you please guide me on how to fix the failing PR Validation

**Comment by onovotny** [comment]
The api approval tests are failing. Not sure why there's a nullref on the CI instead of a real error message, but if you run the tests locally it should show up. Please ensure that any api changes are doc'd in the `PublicApiApprovalTest.approve_public_api.approved.txt` file.

Thanks

**Comment by christopherie** [comment]
@onovotny thank you for the guidance. I have updated the PublicApiApprovalTest.approve_public_api.approved.txt file, but I get the same test errors. Could this be a solution? http://www.codewrecks.com/blog/index.php/2017/05/27/error-during-dotnet-restore-in-a-vsts-build/

**Comment by onovotny** [comment]
@christopherie I don't think so, it's still something in the approval tests not working:

```
2018-06-16T08:22:05.0038307Z  System.NullReferenceException : Object reference not set to an instance of an object.
2018-06-16T08:22:05.0038535Z Stack Trace:
2018-06-16T08:22:05.0038970Z    at ApprovalTests.Reporters.XUnitReporter.InvokeEqualsMethod(Type type, String[] parameters)
2018-06-16T08:22:05.0039222Z    at ApprovalTests.Reporters.AssertReporter.AssertEqual(String approvedContent, String receivedContent)
2018-06-16T08:22:05.0039486Z    at ApprovalTests.Reporters.AssertReporter.AssertFileContents(String approved, String received)
2018-06-16T08:22:05.0039735Z    at ApprovalTests.Reporters.AssertReporter.Report(String approved, String received)
2018-06-16T08:22:05.0039964Z    at ApprovalTests.Reporters.FirstWorkingReporter.Report(String approved, String received)
2018-06-16T08:22:05.0040230Z    at ApprovalTests.Reporters.ContinousDeliveryUtils.ReportOnServer(String approved, String received)
2018-06-16T08:22:05.0040464Z    at ApprovalTests.Reporters.TfsVnextReporter.Report(String approved, String received)
2018-06-16T08:22:05.0040822Z    at ApprovalTests.Reporters.FirstWorkingReporter.Report(String approved, String received)
2018-06-16T08:22:05.0041178Z    at ApprovalTests.Approvers.FileApprover.ReportFailure(IApprovalFailureReporter reporter)
2018-06-16T08:22:05.0041514Z    at ApprovalTests.Core.Approver.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter)
2018-06-16T08:22:05.0042577Z    at ApprovalTests.Approvals.Verify(IApprovalWriter writer, IApprovalNamer namer, IApprovalFailureReporter reporter)
2018-06-16T08:22:05.0042814Z    at ApprovalTests.Approvals.Verify(IApprovalWriter writer)
2018-06-16T08:22:05.0043024Z    at ApprovalTests.Approvals.Verify(String text)
2018-06-16T08:22:05.0043220Z    at Humanizer.Tests.ApiApprover.PublicApiApprovalTest.approve_public_api()
2018-06-16T08:22:06.7261733Z Results File: D:\a\_temp\VssAdministrator_factoryvm-az365_2018-06-16_08_21_40.trx
2018-06-16T08:22:06.7262330Z 
2018-06-16T08:22:06.7262660Z Total tests: 8449. Passed: 8448. Failed: 1. Skipped: 0.
```
If you run the build script locally, it should pop-up a diff of the issue, have you tried that?

**Comment by christopherie** [comment]
@onovotny hi there. I see the VSTS:Humanizer -PR Validation status is not updating. Is there more that I need to do?

**Comment by onovotny** [comment]
@christopherie GitHub still shows conflicts on the `src/Humanizer.Tests/PublicApiApprovalTest.approve_public_api.approved.txt`. The CI should run once that's resolved.

**Comment by SimonCropp** [comment]
@christopherie  can you add some docs that explain the use case and how it works

**Comment by SimonCropp** [comment]
closing since underlying issue is closed https://github.com/Humanizr/Humanizer/issues/694

**Pull request closed without merging**
